# Generated by Django 5.2.13 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("primary_color", models.CharField(default="#6366f1", max_length=7)),
                ("secondary_color", models.CharField(default="#8b5cf6", max_length=7)),
                ("accent_color", models.CharField(default="#ec4899", max_length=7)),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("text_color", models.CharField(default="#1f2937", max_length=7)),
                (
                    "font_family",
                    models.CharField(default="'Inter', sans-serif", max_length=100),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("rounded", "Rounded"),
                            ("pill", "Pill-shaped"),
                            ("square", "Square"),
                        ],
                        default="rounded",
                        max_length=20,
                    ),
                ),
                (
                    "card_style",
                    models.CharField(
                        choices=[
                            ("shadow", "Shadow"),
                            ("border", "Border"),
                            ("flat", "Flat"),
                        ],
                        default="shadow",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
